version: '3'

services:
  projects:
    build:
      context: .
      dockerfile: Dockerfile-projects
    image: 'projects'
    ports:
      - "8888:8888"
    environment:
      PROJECT_PATH: '/src'
    volumes:
      - ./common:/common:ro
      - ./projects:/src/projects
      - ./materials:/src/materials
    entrypoint: /common/entry.sh
